on:
  push:
    branches:
    - main
    tags:
    - 'v*'

name: Release policy

jobs:

  test:
    name: run tests and linters
    uses: viccuad/github-actions/.github/workflows/reusable-test-policy-go.yml@v3

  release:
    needs: test
    permissions:
      # Required to create GH releases
      contents: write
      # Required to push to GHCR
      packages: write
      # Required by cosign keyless signing
      id-token: write

    uses: viccuad/github-actions/.github/workflows/reusable-release-policy-go.yml@v3
    with:
      oci-target: ghcr.io/${{ github.repository_owner }}/policies/hostpaths-psp
